### PR TITLE
sriov: support for tolerations

### PR DESCRIPTION
**Pull request by jasonhancock**
I need to add a toleration to the daemonsets.

I wasn't sure if I should bump the chart version in Chart.yaml....please let me know if you want me to increment it.

### CODE REVIEW

**Comment by jasonhancock** [comment]
@dougbtv @mukesh-dua any thoughts?

**Comment by jasonhancock** [comment]
bump

**Comment by jasonhancock** [comment]
@dougbtv @mukesh-dua any thoughts?

**Review by jdambly-ns — APPROVED** [review]
LGTM

**Review by e0ne — APPROVED** [review]

**Pull request merged**
